### ISSUE TITLE
packaging: CLI command that builds an app package (`app.zip`)

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#511]
# Requirement

a Partner can execute `az partnercenter marketplace offer package build` that can build the following: 

1. a standard app.zip package with a mainTemplate.json, etc.
2. an "installer" mode that creates a MODM spec'd `app.zip` package

When app installer (MODM) is selected, additional 

## Success Criteria

- Validates all required files are present
- structures the contents of app.zip according to spec (standard, and modm)
- Python library is created and published for CLI to consume
- Build is updated to call python library to create app.zip

## Justification
- partners need a way to build an app package through the CLI 

# Proposed Implementation
- Library (python) is created that conforms to the specification just for modm app package
   - Lib is published publicly and referenced by the CLI
- The standard app packaging process is written directly in the CLI codebase

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/524
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/527
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/525
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/537
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/541
- [x] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/553
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/554
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/555
- [x] bug: raise validation error for missing type in TerraformInputVariable
```

# Cross References

- [CLI command for managed applications](https://github.com/Azure/partnercenter-cli-extension/issues/217)
-
