### ISSUE TITLE
Add Azure Function that performs a HTTP Redirect to dashboard URL

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#522]
# Implementation

The Azure function should be published to a known name from the virtual machine.  Service Host should deploy prior to starting containers
```[tasklist]
### Tasks
- [x] Implemented this through App Service after Azure Function, moving the client app / frontend spa to a separate csproj for complication.
- [x] Restructure solution projects
- [x] Update build and packaging to include clientapp.zip
```
