### ISSUE TITLE
ui: cycle 2 frontend / client app updates

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#569]
```[tasklist]
### Tasks
- [x] Login view to use separate template without sidebar menu
- [x] Error message needs to display on login failure
- [x] Diagnostics should flow / update as changes occur "realtime
- [x] Loading message should read "Starting up..." and add margin from header so it looks a little nicer
- [x] Reduce Starting... message checks to 2 seconds
- [x] Add message in login stating to use credentials from "Installer settings"
- [x] Update viewDefinition.json to include message stating to use credentials from "installer settings" step
- [x] Delete command button text: "Delete installer"
```
