### ISSUE TITLE
Infrastructure: speed up App Service start up time

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#570]
S1 plan is slow to start. Experiment and choose optimal plan for start times
```[tasklist]
### Tasks
- [ ] Select optimal app service plan
- [ ] Evaluate configuration settings
- [ ] Confirm exposed port number isn't slowing start times
```
