### ISSUE TITLE
security: Implement basic authentication

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#571]
```[tasklist]
### Tasks
- [x] Add username | password fields to create UI definition and add template finalizer to python library
- [x] Incorporate basic JWT authentication / authorization in ServiceHost, WebHost, and backend of ClientApp
- [x] Add central App Configuration store for values and secrets for JWT configuration
```
