### ISSUE TITLE
ui: frontend updates

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#574]
```[tasklist]
### Tasks
- [x] create json file proxy for debugging frontend without backend infra
- [x] update logo on sign in
- [x] remove the "modm" from the sign in indicator and use "Administrator
- [x] move commands above properties area
```
