### ISSUE TITLE
cleanup: omnibus of clean up tasks

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#617]
```[tasklist]
### Tasks
- [x] build: add sas token during app.zip URL creation for service catalog app
- [x] clean up verbiage in viewDefinition.json
- [x] build: update major version and minor version to 2.0
- [x] ux: set step title to "App Installer settings"
```
